### ISSUE TITLE
Deploy as -> Dashboard to Jupyter Dashboard Server

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_bundlers#12]
Write a bundler that takes a notebook and POSTs it to a  `jupyter-incubator/dashboards_nodejs_app` instance (now called Jupyter Dashboard Server for simplicity). Reads the URL of the dashboard server from an environment variable set when the Jupyter Notebook Server is brought up (e.g., `DASHBOARD_SERVER_URL`).

Only posts the notebook for the time being, no additional dependencies and associated resources (because that's all the POST handler supports in the dashboard server).

* [x] Initially, do a PR that does the POST assuming there's no auth on the dashboard server.
* [x] Later, after jupyter-incubator/dashboards_nodejs_app#45 lands, do another PR that sends the proper auth token along in the POST. The auth token will be read out of the environment on the Notebook server side as well (`DASHBOARD_SERVER_TOKEN`).

**Comment by parente** [comment]
Started impl. Don't have an answer for testing yet. Strawman: Run `make build dev` here to get the bundler working. Just hardcode (to start) the IP address of the dashboard server started by `make run` or `make dev` over there. Later, make than an env var.

**Comment by nitind** [comment]
Manual testing of the basic notebook upload with the dashboard server, unprotected and hacked into the Makefile dev target, is working.

**Comment by parente** [comment]
To finish this off:

* Update the README
* Update the Makefile so it's easy to pass the dashboard server URL and auth token in the `make dev` target
