### ISSUE TITLE
HTTP error while using jupyterhub

### ISSUE THREAD

**Issue by ultraseven** [jupyter-incubator/dashboards_bundlers#31]
While using jupyterhub, a HTTP 500 error with "No dashboard server configured" message returned after click menu "Deploy as"->"Dashboard on jupyter dashboard server". 
Env var DASHBOARD_SERVER_URL="http://dashboards:3000/" already set.

**Comment by parente** [comment]
Is the dashboards hostname actually a server name in your jupyterhub setup?

**Comment by ultraseven** [comment]
of course, I use docker-compose to link them.

**Comment by parente** [comment]
OK. Just trying to envision the setup you've got. We've not tried any of this with JHub. If you can share your docker-compose.yml that would help.

Another guess: is the DASHBOARD_SERVER_URL env var set on the notebook container within Jupyter Hub, not the Hub server container?

**Comment by ultraseven** [comment]
I modified yml file on this: https://gist.github.com/parente/527cea0481afe9fabbcd
I made an image by adding jupyterhub into the jupyterbox/notebook.
Then the 'image' is set to 'my-notebook', and 'ports' is set to '8000:8000'.
Jupyterhub runs well expect "deploy as" functions return HTTP 500.

**Comment by parente** [comment]
If you swapped Jupyter Hub in place of the notebook entry in that gist, I don't think the env var is going to be set on the notebook servers spawned by jupyter hub necessarily.  If you can share your docker-compose.yml as a gist, it'll help so we can better understand your setup.

/cc @jtyberg

**Comment by ultraseven** [comment]
Here are my yml and dockerfile:https://gist.github.com/ultraseven/05a8992aacffca81d02064be8a53e1d8

**Comment by jtyberg** [comment]
@ultraseven Your setup has me a little confused.  I assume you're using the default JupyterHub LocalProcessSpawner to spawn Notebook servers within the `notebook` container in your YAML configuration.

Regardless, I think @parente is on the right track.  JupyterHub keeps only select environment variables when spawning Notebook servers, and adds a few of its own.  Unless you specify additional environment variables in the `jupyterhub_config.py`, they will not be passed onto spawned Notebook servers by default.  You have to pass them on explicitly.

```
c.Spawner.environment = { 'DASHBOARD_SERVER_URL': os.environ.get('DASHBOARD_SERVER_URL') }
```

If you have a Notebook server running, you can confirm if `DASHBOARD_SERVER_URL` is in the  environment:

```
import os 
os.environ
```

**Comment by ultraseven** [comment]
Thanks to @jtyberg and @parente 
I add this to jupyterhub_config.py then they work.
```
c.Spawner.env_keep.append('DASHBOARD_SERVER_URL')
c.Spawner.env_keep.append('DASHBOARD_REDIRECT_URL')
c.Spawner.env_keep.append('DASHBOARD_SERVER_AUTH_TOKEN')
```
