### ISSUE TITLE
"Deploy as" missed in the File menu

### ISSUE THREAD

**Issue by alexoor** [jupyter-incubator/dashboards_bundlers#43]
After installed Dashboards package, I can find Dashboard Layout item in View. 
However, it does not have "Deploy as" item in the File after I installed the dashboards_bundler package and activate the extension. Do you know how to debug it?

Thank you in advance!
Alex

**Comment by parente** [comment]
Make sure you fully activate the prerequisite `jupyter_cms` extension:

`jupyter cms quick-setup --sys-prefix`

We've had a few people ask about this so far. Either we need to make our README more explicit about it or somehow automate it.

**Comment by alexoor** [comment]
problem solved!!!

Really appreciate your quick reply

**Comment by parente** [comment]
@alexoor Glad that was it.

I'm going to reopen this issue as a way to track the update to the README or the automation of the dependent extension.
