### ISSUE TITLE
bundle_index raises CryptoGen error on Windows

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_bundlers#48]
The error is:
```
RuntimeError: nbconvert wrote to stderr: b'Fatal Python error: Failed to initialize Windows random API (CryptoGen)\r\n'
```
The issue lies an an empty environment being passed in
https://github.com/jupyter-incubator/dashboards_bundlers/blob/master/dashboards_bundlers/local_deploy/__init__.py#L85

The underlying issue is due to a known Python 3 bug, whereby a `dll` cannot be loaded when `SystemRoot` env variable is not set: https://bugs.python.org/issue20614

See how `django` solve this issue:
https://github.com/django/django/commit/5338ff4808c822a8b00e90154b884b7be3011e60

Please feel free to assign to me to create a pull request for this.

**Comment by rs2** [comment]
Why not simply replace `{}` with `dict(os.environ)`? That works on Windows.

**Comment by jhpedemonte** [comment]
Are there any potentially bad side effects to passing the full env (ie security, etc)?  I noticed that the django code only passes in a few env vars.

cc @nitind

**Comment by nitind** [comment]
@jhpedemonte The full environment would include the local username and other details we don't need/want, so yes, I think just passing in the SystemRoot is advisable.
