### ISSUE TITLE
ipywidgets.widgets.Text not rendered in a local dashboard, whereas Textarea is

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_bundlers#51]
See [dashboard](http://jupyter.cloudet.xyz/user/qmSa89seVMg9/files/local_dashboards/foobar/index.html) or try the following code:

```python
from ipywidgets import widgets, interact
from IPython.display import display

def f(x):
    return x

interact(f, x=widgets.Text('foo'));

interact(f, x=widgets.Textarea('bar'));
```

The js error is `Error: Could not determine where the display message was from.  Widget will not be displayed`

**Comment by parente** [comment]
Are the two interacts in the same cell in the notebook?

**Comment by rs2** [comment]
No

**Comment by parente** [comment]
![screen shot 2016-08-19 at 8 46 50 am](https://cloud.githubusercontent.com/assets/153745/17810162/7d7acdf8-65e9-11e6-900b-a1b4cb6becf9.png)

I can't reproduce using the jupyter.cloudet.xyz server with latest Chrome.

**Comment by rs2** [comment]
Publish it as a dashboard? Unfortunately http://jupyter.cloudet.xyz does not have a `dashboards server` configured.

**Comment by parente** [comment]
OK. I misread local meaning within the notebook.

I do see the behavior you describe, but only ever for the text widget. For example, if I change the code to the following all in one cell:

```
from ipywidgets import widgets, interact
from IPython.display import display

def f(x):
    return x

interact(f, x=widgets.Textarea('bar'))
interact(f, x='123')
_ = interact(f, x=['foo', 'bar', 'baz'])
```

I see the text area and dropdown widgets, but not the text.

I suspect this is a problem with the ipywidgets text widget built into the version of Thebe that is included into the deprecated local deploy option. Probably nothing we can do about it.

**Comment by jhpedemonte** [comment]
And this works as expected when deploying to Dashboards Server.

**Comment by rs2** [comment]
:+1:
