### ISSUE TITLE
/nbextensions path gets incorrectly appended to the current url

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_bundlers#52]
Once a notebook is deployed as a local dashboard, you get 404s in the console on URLs like 

`http://server-name:8888/files/local_dashboards/demo_dashboard/static/nbextensions/widgets/widgets/css/widgets.min.css`

The correct URL should be

`http://server-name:8888/nbextensions/widgets/widgets/css/widgets.min.css`

Can you help me locate the code responsible for generation of the 1st (incorrect) URL?

**This is a high-impact issue as no custom/installed nbextensions can be referenced in the local_dashboards mode.**

**Comment by rs2** [comment]
Occurs on both Windows and Unix; e.g. see
`http://jupyter.cloudet.xyz/user/AlIziED7KCQ1/files/local_dashboards/import_error_demo/index.html`

You get: 
`http://jupyter.cloudet.xyz/user/AlIziED7KCQ1/files/local_dashboards/import_error_demo/static/nbextensions/widgets/widgets/css/widgets.min.css Failed to load resource: the server responded with a status of 404 (Not Found)`

Whereas 
`http://jupyter.cloudet.xyz/user/AlIziED7KCQ1/nbextensions/widgets/widgets/css/widgets.min.css`
works fine.

The notebook is:
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "42"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "42"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

**Comment by jhpedemonte** [comment]
Local dashboards are deprecated (see README) and we haven't been testing it. The preferred use case is to deploy to the [dashboards server](https://github.com/jupyter-incubator/dashboards_server).

**Comment by rs2** [comment]
Are there any examples showing how to use the dashboard once it is deployed to the server? I know it must be trivial, but the [jupyter.cloudet.xyz](http://jupyter.cloudet.xyz/user/1Dc2XYMCG0cy/api/bundlers/dashboards_server_upload?notebook=dashboards%2Fgot_scotch_demo%2Fscotch_dashboard_declarative.ipynb) deployment gives a 500 error, and the [docker image](https://hub.docker.com/r/jupyterincubator/dashboards-widgets-cm-notebook/) does not have the server installed?

**Comment by parente** [comment]
Here's a few resources:

* https://github.com/jupyter-incubator/dashboards_setup - recipes for deploying notebook server, dashboard server, kernel gateway, and the notebook extensions
* http://blog.ibmjstart.net/2016/04/26/2822/ - blog post about the above (I think it still refers to the older gist version which became the repo above)
* https://github.com/ibm-et/pydata2016 - tutorial for the upcoming http://pydata.org/carolinas2016/ conference about building and deploying dashboards from notebooks

**Comment by rs2** [comment]
`jupyter-dashboards-server --IP 0.0.0.0` says `POST /api/kernels?<kernel id> 500 0.619 ms - -`. How to debug/fix it?

**Comment by parente** [comment]
You need to point the dashboard server at a kernel gateway instance. The dashboards_setup/docker_deploy folder has a docker-compose file with the various settings you need to mimic if you're not using that recipe directly.

**Comment by rs2** [comment]
Thank you, got the converted `ipynb` appear in the dashboards server on `http://host:3000/dashboards/my_demo`, but the browser says `Uncaught (in promise) Error: Object 'ipython.widget' not found in registry`, and Kernel Gateway log has `[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version`. 

How do I get those elements registered?

Getting there, but any pointers would be appreciated!

**Comment by rs2** [comment]
I docker-compose the dashboards-setup project, publish a dummy notebook to a dashboards server, and get this error in the console:
```
dashboard.js:258stderr Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

**Comment by parente** [comment]
@rs2 Are the widgets working even with that error? I believe that error gets logged all the time because ipywidgets is checking with its backend to see if the JS is available. But in the case of the dashboards server, the backend (kernel gateway) is headless and has nothing to do with serving up the JS.

**Comment by rs2** [comment]
Too many questions on this thread. Let me close it. 

The key issue is there is a limited set of versions of python, ipython, jupyter , kernel-gateway that make dashboards work. I will want to understand what are the constraints, and what are the permissible combinations.
