### ISSUE TITLE
How to disable the deprecated way of publishing local dashboards?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_bundlers#55]
Via `File / Deploy as / Local Dashboard`

**Comment by parente** [comment]
The extension puts three entries, one per menu item, in the nbconfig/notebook.json file in the location you picked during install (--sys-prefix or --user or system level). You can use the jupyter bundlers command documents in the jupyter_cms project to disable them or manually remove them.

**Comment by rs2** [comment]
:+1:
