### ISSUE TITLE
404 : Not Found

### ISSUE THREAD

**Issue by etikhomolov** [jupyter-incubator/dashboards_bundlers#59]
Going to:

File -> Download as -> Jupyter Dashboard Server Bundle (.zip) gives an error in the browser "404 : Not Found. You are requesting a page that does not exist!"  and at the console:

404 GET /api/bundlers/dashboards_server_download?notebook=StripCharts%2FStripCharts-OLIS.ipynb (::1) 2.32ms referer=http://localhost:8888/notebooks/StripCharts/StripCharts-OLIS.ipynb
--------------------------------------------
CentOS 7. Jupyter Notebook 4.2.3 from anaconda3.
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Current Kernel Information:

Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.

**Comment by etikhomolov** [comment]
I found the source of the error. It is my .jupyter folder. When I removed everything except the file "migrated" the error disappeared. Now I am facing the next problem: dashboard server gives blank screen without any GUI elements. Only narrow blue line at the top

**Comment by parente** [comment]
@etikhomolov I'm going to close this issue since there seems to be more discussion over in #58 about the same issues. See this comment https://github.com/jupyter-incubator/dashboards_bundlers/issues/58#issuecomment-2740584 for the latest.
