### ISSUE TITLE
No GUI elements when running Dashboard with "Deploy as Local Dashboard" and with Dashboard Server

### ISSUE THREAD

**Issue by etikhomolov** [jupyter-incubator/dashboards_bundlers#60]
I tried both "Deploy as Local Dashboard" and "Download as Jupyter Dashboards Server Bundle". The behavior is the same: no GUI elements. Only narrow blue line at the top of the screen. No errors.

CentOS 7. Jupyter Notebook 4.2.3 from anaconda3.
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul 2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Current Kernel Information:

Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul 2 2016, 17:53:06)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.

**Comment by etikhomolov** [comment]
I tried matplotlib and ipywidgets. No luck.

**Comment by parente** [comment]
Let's continue in https://github.com/jupyter-incubator/dashboards_bundlers/issues/58#issuecomment-274058418 where there seems to be more back and forth.
