### ISSUE TITLE
extensionapp is not there, but is referred to in setup.py; install fails if setuptools are present

### ISSUE THREAD

**Issue by daliati** [jupyter-incubator/dashboards_bundlers#64]
The setup refers to dashboards_bundlers.extensionapp: https://github.com/jupyter-incubator/dashboards_bundlers/blob/master/setup.py#L61, but the extensionapp.py is gone since the previous release? If setuptools are in sys.modules, install fails.

**Comment by parente** [comment]
Doh! You're right. I'll cut a 0.9.1 release sometime today with the fix.

I'm surprised the install on travis didn't catch this: https://github.com/jupyter-incubator/dashboards_bundlers/blob/master/.travis.yml#L15

**Comment by daliati** [comment]
Thanks a lot!
