### ISSUE TITLE
jupyter-dashboards-bundlers-0.9.1 not compatible with latest jupyter?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_bundlers#66]
Repro steps:

1. Create a conda environment `conda create -n foo jupyter python`
1. Activate `foo`
1. Verify that the spec includes:
```
ipykernel:          4.6.1-py36_0
ipython:            6.0.0-py36_0
ipython_genutils:   0.2.0-py36_0
jupyter:            1.0.0-py36_3
jupyter_client:     5.0.1-py36_0
jupyter_console:    5.1.0-py36_0
jupyter_core:       4.3.0-py36_0
notebook:           5.0.0-py36_0
```
1. Run `pip install jupyter_dashboards-bundlers`
1. Verify that `jupyter-dashboards-bundlers-0.9.1` gets installed
1. Try running `jupyter dashboards_bundlers quick-setup --sys-prefix`
1. You get `[Errno 'jupyter-dashboards_bundlers' not found] 2`
1. Try `jupyter bundlerextension enable --sys-prefix --py dashboards_bundlers`
1. You get `[Errno 'jupyter-bundlerextension' not found] 2`

**Comment by parente** [comment]
The `jupyter-dashboard-bundlers` CLI no longer exists. The bundler support is built into Notebook 5.0+. See the README here for the up to date install instructions: https://github.com/jupyter-incubator/dashboards_bundlers#installing-and-enabling
