### ISSUE TITLE
Deploying bundled nb with associated files raises 500: Internal Server Error

### ISSUE THREAD

**Issue by vmarchen** [jupyter-incubator/dashboards_bundlers#67]
Hi. I am following the Docker deployment example [found here](https://github.com/jupyter-incubator/dashboards_setup/tree/master/docker_deploy) very closely but using the base image `jupyter/scipy-notebook:11be019e4079` (so Jupyter 5.0.x). Everything works when the notebooks are entirely self-contained; I can run them, widgets work, I deploy to Dashboard Server, they function. My issue comes when the notebooks rely on external files, e.g. I pull out a simple plot (that works if inside the nb) into a separate script or I load a csv that's associated like so:
`<!--associate:`
`data/`
`-->`
but then get a `500: Internal Server Error` when trying to deploy. My dashboard URL environment vars should be set (I think), and again this only happens for non-standalone notebooks. Not sure if I'm missing something simple? Thanks!

**Comment by vmarchen** [comment]
Here's an example with Dockerfiles and two notebooks. Notebooks contain the same info, but one loads a plot from an external script and the other doesn't.
[example.zip](https://github.com/jupyter-incubator/dashboards_bundlers/files/1072157/example.zip)

**Comment by Skhon09** [comment]
Hi,
Did you fix?
I'm having the same issue with the declarative widgets. 
Maybe this is related.
Thanks

**Comment by vmarchen** [comment]
Hi, @Skhon09. My issue was irrespective of using declarative widgets, so I probably can't help. I resolved to run the dashboard/notebook/gateway servers outside of Docker containers, and everything works fine now (both widgets and associated data).
